##**Exercise 3 - Web Scraping**

### Requests

https://pypi.org/project/requests/


Docs: https://requests.readthedocs.io/en/latest/

kita coba scrape https://www.kopikenangan.com/

In [ ]:
import requests

In [ ]:
page = requests.get('https://www.kopikenangan.com/', headers={'User-Agent': 'Mozilla/5.0'})
page

In [ ]:
# get the html document
print(page.text[:2000])

<!doctype html>
<html xmlns:og="http://opengraphprotocol.org/schema/" xmlns:fb="http://www.facebook.com/2008/fbml" lang="en-US"  >
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- This is Squarespace. --><!-- tuatara-helicon-5zcd -->
<base href="">
<meta charset="utf-8" />
<title>Kopi Kenangan</title>
<meta http-equiv="Accept-CH" content="Sec-CH-UA-Platform-Version, Sec-CH-UA-Model" /><link rel="icon" type="image/x-icon" href="https://images.squarespace-cdn.com/content/v1/5fa1095912d2fc6dfc63ac9c/d015c1ed-ca4f-4546-898e-7c4afa629286/favicon.ico?format=100w"/>
<link rel="canonical" href="https://kopikenangan.com"/>
<meta property="og:site_name" content="Kopi Kenangan"/>
<meta property="og:title" content="Kopi Kenangan"/>
<meta property="og:url" content="https://kopikenangan.com"/>
<meta property="og:type" content="website"/>
<meta property="og:description" content="Kopi Kenangan is one of the fastest growing grab-and-go coffee chain in Indonesia."/>
<meta property="og:image" content="http://static1.squarespace.com/static/5fa1095912d2fc6dfc63ac9c/t/697c394bfb54b313960b7240/1769748811604/Kopi+Kenangan+Logo.png?format=1500w"/>
<meta property="og:image:width" content="850"/>
<meta property="og:image:height" content="355"/>
<meta itemprop="name" content="Kopi Kenangan"/>
<meta itemprop="url" content="https://kopikenangan.com"/>
<meta itemprop="description" content="Kopi Kenangan is one of the fastest growing grab-and-go coffee chain in Indonesia."/>
<meta itemprop="thumbnailUrl" content="http://static1.squarespace.com/static/5fa1095912d2fc6dfc63ac9c/t/697c394bfb54b313960b7240/1769748811604/Kopi+Kenangan+Logo.png?format=1500w"/>
<link rel="image_src" href="http://static1.squarespace.com/static/5fa1095912d2fc6dfc63ac9c/t/697c394bfb54b313960b7240/1769748811604/Kopi+Kenangan+Logo.png?format=1500w" />
<meta itemprop="image" content="http://static1.squarespace.com/static

## Web Scraping with HTTP Request

### HTML Parser using BeautifulSoup

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
# get the html document
import requests
page = requests.get('https://www.kopikenangan.com/', headers={'User-Agent': 'Mozilla/5.0'})
bs = BeautifulSoup(page.text, 'html.parser')
bs.title

### **tagging** in html

In [ ]:
# get title of the page
bs.title

In [ ]:
bs.title.name

'title'

In [ ]:
bs.title.text

'Kopi Kenangan'

In [ ]:
# lihat heading pertama yang ketemu
bs.h1

In [ ]:
# lihat link pertama yang ketemu
bs.a

<a class="icon icon--stroke icon--fill icon--cart sqs-custom-cart" href="/cart">
<span class="Cart-inner">
<svg class="icon icon--cart" height="49" viewbox="0 0 61 49" width="61">
<path clip-rule="evenodd" d="M0.5 2C0.5 1.17157 1.17157 0.5 2 0.5H13.6362C14.3878 0.5 15.0234 1.05632 15.123 1.80135L16.431 11.5916H59C59.5122 11.5916 59.989 11.8529 60.2645 12.2847C60.54 12.7165 60.5762 13.2591 60.3604 13.7236L50.182 35.632C49.9361 36.1614 49.4054 36.5 48.8217 36.5H18.0453C17.2937 36.5 16.6581 35.9437 16.5585 35.1987L12.3233 3.5H2C1.17157 3.5 0.5 2.82843 0.5 2ZM16.8319 14.5916L19.3582 33.5H47.8646L56.6491 14.5916H16.8319Z" fill-rule="evenodd"></path>
<path d="M18.589 35H49.7083L60 13H16L18.589 35Z"></path>
<path d="M21 49C23.2091 49 25 47.2091 25 45C25 42.7909 23.2091 41 21 41C18.7909 41 17 42.7909 17 45C17 47.2091 18.7909 49 21 49Z"></path>
<path d="M45 49C47.2091 49 49 47.2091 49 45C49 42.7909 47.2091 41 45 41C42.7909 41 41 42.7909 41 45C41 47.2091 42.7909 49 45 49Z"></path>
</svg>
<div class="legacy-cart icon-cart-quantity">
<span class="sqs-cart-quantity">0</span>
</div>
</span>
</a>

 ### find and find_all

In [ ]:
# cari 1 heading h2 pertama (biasanya section "News")
bs.find("h2")

In [ ]:
# cari SEMUA heading h4 (biasanya judul tiap berita/promo)
bs.find_all("h4")

[<h4 style="text-align:center;white-space:pre-wrap;">Halal certification<br/></h4>,
 <h4 data-rte-preserve-empty="true" style="text-align: center; ; white-space:pre-wrap;"><strong>WORLD BEST BRAND WINNER 2025-2026</strong></h4>,
 <h4 style="text-align:center;white-space:pre-wrap;">COFFEE JOURNEY</h4>,
 <h4 data-rte-preserve-empty="true" style="text-align: center; ; white-space:pre-wrap;"><strong><em>Follow Us on Instagram</em></strong><a href="https://www.instagram.com/kopikenangan.id"> @kopikenangan.id</a></h4>]

In [ ]:
# cari semua link promo/menu (tag <a>)
bs.find_all('a')[:10]

[<a class="icon icon--stroke icon--fill icon--cart sqs-custom-cart" href="/cart">
 <span class="Cart-inner">
 <svg class="icon icon--cart" height="49" viewbox="0 0 61 49" width="61">
 <path clip-rule="evenodd" d="M0.5 2C0.5 1.17157 1.17157 0.5 2 0.5H13.6362C14.3878 0.5 15.0234 1.05632 15.123 1.80135L16.431 11.5916H59C59.5122 11.5916 59.989 11.8529 60.2645 12.2847C60.54 12.7165 60.5762 13.2591 60.3604 13.7236L50.182 35.632C49.9361 36.1614 49.4054 36.5 48.8217 36.5H18.0453C17.2937 36.5 16.6581 35.9437 16.5585 35.1987L12.3233 3.5H2C1.17157 3.5 0.5 2.82843 0.5 2ZM16.8319 14.5916L19.3582 33.5H47.8646L56.6491 14.5916H16.8319Z" fill-rule="evenodd"></path>
 <path d="M18.589 35H49.7083L60 13H16L18.589 35Z"></path>
 <path d="M21 49C23.2091 49 25 47.2091 25 45C25 42.7909 23.2091 41 21 41C18.7909 41 17 42.7909 17 45C17 47.2091 18.7909 49 21 49Z"></path>
 <path d="M45 49C47.2091 49 49 47.2091 49 45C49 42.7909 47.2091 41 45 41C42.7909 41 41 42.7909 41 45C41 47.2091 42.7909 49 45 49Z"></path>
 </svg>
 <div class="legacy-cart icon-cart-quantity">
 <span class="sqs-cart-quantity">0</span>
 </div>
 </span>
 </a>,
 <a class="header-skip-link sqs-button-element--primary" href="#page">
         Skip to Content
       </a>,
 <a data-animation-role="header-element" href="/">
 <img alt="Kopi Kenangan" data-loader="raw" decoding="async" elementtiming="nbf-header-logo-desktop" fetchpriority="high" loading="eager" src="//images.squarespace-cdn.com/content/v1/5fa1095912d2fc6dfc63ac9c/16a01780-2021-4d5a-ba44-00bed1e15992/Kopi+Kenangan+Logo.png?format=1500w" style="display:block"/>
 </a>,
 <a aria-current="page" data-animation-role="header-element" href="/">
         Home
       </a>,
 <a data-animation-role="header-element" href="/vip">
         VIP
       </a>,
 <a href="/dreamy-choco-series">
 <span class="header-nav-folder-item-content">
                   Dreamy Choco Series
                 </span>
 </a>,
 <a href="/kenangan-beans">
 <span class="header-nav-folder-item-content">
                   Kenangan Beans
                 </span>
 </a>,
 <a href="/petualangan-rasa-onepiece-tahilalats">
 <span class="header-nav-folder-item-content">
                   Petualangan Rasa - One Piece x Tahilalats
                 </span>
 </a>,
 <a href="/kiss-food-selection">
 <span class="header-nav-folder-item-content">
                   KISS &amp; Food Selection
                 </span>
 </a>,
 <a href="/pasal-pasanganideal">
 <span class="header-nav-folder-item-content">
                   Pasangan Ideal
                 </span>
 </a>]

In [ ]:
news_titles = bs.find_all('h4')
for i in news_titles:
  print(i.text.strip())

Halal certification
WORLD BEST BRAND WINNER 2025-2026
COFFEE JOURNEY
Follow Us on Instagram @kopikenangan.id

In [ ]:
promo_links = bs.find_all('a')
for i in promo_links:
  href = i.get('href')
  text = i.text.strip()
  if href and text:
    print(text, '->', href)

0 -> /cart
Skip to Content -> #page
Home -> /
VIP -> /vip
Dreamy Choco Series -> /dreamy-choco-series
Kenangan Beans -> /kenangan-beans
Petualangan Rasa - One Piece x Tahilalats -> /petualangan-rasa-onepiece-tahilalats
KISS & Food Selection -> /kiss-food-selection
Pasangan Ideal -> /pasal-pasanganideal
Pesta Cashback -> /pesta-cashback
Outlets -> /outlets
Big Order -> /big-order
About -> /about
News -> /news
Kenangan Academy -> /kenangan-academy
Career -> /career
Download App -> /download-app
Home -> /
VIP -> /vip
Dreamy Choco Series -> /dreamy-choco-series
Kenangan Beans -> /kenangan-beans
Petualangan Rasa - One Piece x Tahilalats -> /petualangan-rasa-onepiece-tahilalats
KISS & Food Selection -> /kiss-food-selection
Pasangan Ideal -> /pasal-pasanganideal
Pesta Cashback -> /pesta-cashback
Outlets -> /outlets
Big Order -> /big-order
About -> /about
News -> /news
Kenangan Academy -> /kenangan-academy
Career -> /career
Download App -> /download-app
Home -> /
VIP -> /vip
Folder:
Order -> /promo-folder/
Back -> /
Dreamy Choco Series -> /dreamy-choco-series
Kenangan Beans -> /kenangan-beans
Petualangan Rasa - One Piece x Tahilalats -> /petualangan-rasa-onepiece-tahilalats
KISS & Food Selection -> /kiss-food-selection
Pasangan Ideal -> /pasal-pasanganideal
Pesta Cashback -> /pesta-cashback
Outlets -> /outlets
Big Order -> /big-order
Folder:
About -> /about-folder/
Back -> /
About -> /about
News -> /news
Kenangan Academy -> /kenangan-academy
Career -> /career
Download App -> /download-app
Learn More -> /news
Outlet Terdekat -> https://www.google.com/maps/search/kopi+kenangan/
Aplikasi Kopi Kenangan -> https://kopikenangan.onelink.me/4u50/tabak
@kopikenangan.id -> https://www.instagram.com/kopikenangan.id

### Simpan hasil scraping ke DataFrame

In [ ]:
news = []

In [ ]:
news_titles = bs.find_all('h4')
for i in news_titles:
  news.append(i.text.strip())

In [ ]:
import pandas as pd
df = pd.DataFrame({'Judul_News_Promo': news})
df

                          Judul_News_Promo
0                      Halal certification
1        WORLD BEST BRAND WINNER 2025-2026
2                           COFFEE JOURNEY
3  Follow Us on Instagram @kopikenangan.id

##Scraping Banyak Halaman - Kopi Kenangan

###Algoritma

1. Tentukan alamat url yang akan discrape (di sini pakai daftar nama halaman, bukan nomor, karena Kopi Kenangan gak punya sistem /page/1, /page/2)
2. Buat array kosong sesuai jumlah feature yang akan dimasukkan (di sini ada 3: nama halaman, judul halaman, ringkasan heading)
3. Buat loop dari setiap halaman yang akan diambil
4. Append terhadap array dari setiap tag yang ditemukan

In [ ]:
# LANGKAH 1: tentukan alamat url yang akan discrape
root = 'https://www.kopikenangan.com'
halaman_list = ['/about', '/news', '/career', '/outlets', '/kenangan-academy']

In [ ]:
# LANGKAH 2: buat array kosong sesuai jumlah feature yang mau diambil
nama_halaman = []
judul_halaman = []
isi_teks = []

In [ ]:
# LANGKAH 3: buat loop dari setiap halaman
# LANGKAH 4: append terhadap array dari setiap tag yang ditemukan

for halaman in halaman_list:
  url = root + halaman
  response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
  soup = BeautifulSoup(response.text, 'html.parser')

  # ambil judul halaman (tag <title>)
  judul = soup.title.text.strip() if soup.title else 'Tidak ada judul'

  # ambil semua heading h1-h3 di halaman itu, gabung jadi satu teks
  headings = soup.find_all(['h1', 'h2', 'h3'])
  teks_gabungan = ' | '.join([h.get_text(strip=True) for h in headings if h.get_text(strip=True)])

  # masukin ke array (append)
  nama_halaman.append(halaman)
  judul_halaman.append(judul)
  isi_teks.append(teks_gabungan)

  print(f"Selesai scrape: {halaman}")

len(nama_halaman), len(judul_halaman), len(isi_teks)

df_multipage = pd.DataFrame({
    'Halaman': nama_halaman,
    'Judul': judul_halaman,
    'Ringkasan_Heading': isi_teks
})
df_multipage

Selesai scrape: /about
Selesai scrape: /news
Selesai scrape: /career
Selesai scrape: /outlets
Selesai scrape: /kenangan-academy

,Halaman,Judul,Ringkasan_Heading
0,/about,About — Kopi Kenangan,FIRST SOUTHEAST ASIAN F&B NEW RETAIL UNICORN |...
1,/news,News — Kopi Kenangan,Kopi Kenangan Tunjuk NCT’s HAECHAN sebagai Bra...
2,/career,Career — Kopi Kenangan,About us | OUR MISSION | Our team
3,/outlets,Outlets — Kopi Kenangan,new outlets | 1.289 Outlets in 141 Cities
4,/kenangan-academy,Kenangan Academy — Kopi Kenangan,"Our Vision | Jakarta | Surabaya | Hard Skill, ..."

**WEB SCRAPING WITH API**

**How to use Wikipedia API?**
1. Go to the Wikipedia API endpoint: (https://en.wikipedia.org/w/api.php?utm_)
2. Wikipedia menyediakan API untuk mengambil berbagai data dari artikel Wikipedia.
3. Untuk request sederhana, tidak perlu membuat atau mendapatkan API key.
4. Gunakan parameter API untuk menentukan data yang ingin diambil. contohnya:
*   action=query → mengambil data
*   format=json → menentuan format hasil sebagai JSON
*   prop=extracts → mengambil isi artikel
*   explaintext=True → mengambil teks biasa tanpa format HTML
*   titles=Data science → menentukan artikel yang ingin diambil
5. Kirim request menggunakan Python dengan library **requests**.
6. Tambahkan User-Agent untuk mengidentifikasi aplikasi atau pengguna yang melakukan request.
7. Hasil response dapat diubah menjadi data Python menggunakan **response.json()**

In [ ]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)

In [ ]:
#mencoba request API
import requests
import json

url = 'https://en.wikipedia.org/w/api.php'
params = {"action": "query", "format": "json", "prop": "extracts", "explaintext": True, "titles": "Data science"}
headers = {"User-Agent": "DataScienceStudent/1.0 (your-email@example.com)"}
response = requests.get(url, params=params, headers=headers)
print(response.status_code)

200

In [ ]:
api_request_json = response.json()
api_request_json

{'batchcomplete': '',
 'query': {'pages': {'35458904': {'pageid': 35458904,
    'ns': 0,
    'title': 'Data science',
    'extract': 'Data science is an interdisciplinary academic field that uses statistics, scientific computing, scientific methods, processing, scientific visualization, algorithms, coding (like Python, SQL, and R), and systems to extract or extrapolate knowledge from potentially noisy, structured, or unstructured data. A data scientist is a professional who creates programming code and combines it with statistical knowledge to summarize data.\n\n\n== Scope of data science ==\nData science plays a critical role in modern decision-making by enabling organizations to extract actionable insights from large and complex datasets.\nData science also integrates domain knowledge from the underlying application domain (e.g., natural sciences, information technology, and medicine). Data science is multifaceted and can be described as a science, a research paradigm, a research method, a discipline, a workflow, and a profession.\nData science is "a concept to unify statistics, data analysis, informatics, and their related methods" to "understand and analyze actual phenomena" with data. It uses techniques and theories drawn from many fields within the context of mathematics, statistics, computer science, information science, and domain knowledge. However, data science is distinct from computer science and information science. Turing Award winner Jim Gray imagined data science as a "fourth paradigm" of science (empirical, theoretical, computational, and now data-driven) and asserted that "everything about science is changing because of the impact of information technology" and the data deluge.\nData science is often described as a multidisciplinary and rapidly evolving field because it draws on techniques from diverse areas, such as computer science, statistics, information science, and other subject-specific disciplines. Some researchers argue that the combination of the different fields resembles how information science was decades ago. These similarities help clarify how data science gradually became its own field of study.\n\n\n== Foundations ==\nData science is an interdisciplinary field focused on extracting knowledge from typically large data sets and applying the knowledge from that data to solve problems in other application domains. The field encompasses preparing data for analysis, formulating data science problems, analyzing data, and summarizing these findings. As such, it incorporates skills from computer science, mathematics, data visualization, graphic design, communication, and business.\nVasant Dhar writes that statistics emphasizes quantitative data and description. In contrast, data science deals with quantitative and qualitative data (e.g., from images, text, sensors, transactions, customer information, etc.) and emphasizes prediction and action. Andrew Gelman of Columbia University has described statistics as a non-essential part of data science. Stanford professor David Donoho writes that data science is not distinguished from statistics by the size of datasets or use of computing and that many graduate programs misleadingly advertise their analytics and statistics training as the essence of a data-science program. He describes data science as an applied field growing out of traditional statistics.\n\n\n== Etymology ==\n\n\n=== Early usage ===\nIn 1962, John Tukey described a field he called "data analysis", which resembles modern data science. In 1985, in a lecture given to the Chinese Academy of Sciences in Beijing, C. F. Jeff Wu used the term "data science" for the first time as an alternative name for statistics. Later, attendees at a 1992 statistics symposium at the University of Montpellier  II acknowledged the emergence of a new discipline focused on data of various origins and forms, combining established concepts and principles of statistics and data analysis with computing.\nThe term "data science" has been traced back to 1974, when Peter Naur proposed it as an alternative name to computer science. In his 1974 book Concise Survey of Computer Methods, Peter Naur proposed using the term ‘data science’ rather than ‘computer science’ to reflect the growing emphasis on data-driven methods In 1996, the International Federation of Classification Societies became the first conference to specifically feature data science as a topic. However, the definition was still in flux. After the 1985 lecture at the Chinese Academy of Sciences in Beijing, in 1997 C. F. Jeff Wu again suggested that statistics should be renamed data science. He reasoned that a new name would help statistics shed inaccurate stereotypes, such as being synonymous with accounting or limited to describing data. In 1998, Hayashi Chikio argued for data science as a new, interdisciplinary concept, with three aspects: data design, collection, and analysis.\n\n\n=== Modern usage ===\nIn 2012, technologists Thomas H. Davenport and DJ Patil declared "Data Scientist: The Sexiest Job of the 21st Century", a catchphrase that was picked up even by major-city newspapers like the New York Times and the Boston Globe. A decade later, they reaffirmed it, stating that "the job is more in demand than ever with employers".\nThe modern conception of data science as an independent discipline is sometimes attributed to William S. Cleveland. In 2014, the American Statistical Association\'s Section on Statistical Learning and Data Mining changed its name to the Section on Statistical Learning and Data Science, reflecting the ascendant popularity of data science.\nThe professional title of "data scientist" has been attributed to DJ Patil and Jeff Hammerbacher in 2008. Though it was used by the National Science Board in their 2005 report "Long-Lived Digital Data Collections: Enabling Research and Education in the 21st Century", it referred broadly to any key role in managing a digital data collection.\n\n\n== Data science and data analysis ==\n\nData analysis typically involves working with structured datasets to answer specific questions or solve specific problems. This can involve tasks such as data cleaning and data visualization to summarize data and develop hypotheses about relationships between variables. Data analysts typically use statistical methods to test these hypotheses and draw conclusions from the data.\nData science involves working with larger datasets that often require advanced computational and statistical methods to analyze. Data scientists often work with unstructured data such as text or images and use machine learning algorithms to build predictive models. Data science often uses statistical analysis, data preprocessing, and supervised learning.\n\n\n== Cloud computing for data science ==\n\nCloud computing can offer access to large amounts of computational power and storage. In big data, where volumes of information are continually generated and processed, these platforms can be used to handle complex and resource-intensive analytical tasks.\nSome distributed computing frameworks are designed to handle big data workloads. These frameworks can enable data scientists to process and analyze large datasets in parallel, which can reduce processing times.\n\n\n== Ethical consideration in data science ==\nData science involves collecting, processing, and analyzing data which often includes personal and sensitive information. Ethical concerns include potential privacy violations, bias perpetuation, and negative societal impacts.\nMachine learning models can amplify existing biases present in training data, leading to discriminatory or unfair outcomes.\n\n\n== See also ==\n\nPython (programming language)\nR (programming language)\nData engineering\nBig data\nMachine learning\nArtificial intelligence\nBioinformatics\nAstroinformatics\nTopological data analysis\nList of data science journals\nList of data science software\nList of open-source data science software\nData science notebook software\n\n\n== References =='}}}}

In [ ]:
with open("response.json", "w") as f:
   json.dump(api_request_json, f, indent=4)

In [ ]:
with open("response.json", "r") as f:
    api_request_json = json.load(f)

query = api_request_json["query"]
pages = query["pages"]
page = list(pages.values())[0]

In [ ]:
#simpan ke dataframe
import pandas as pd

title = page["title"]
extract = page["extract"]

df = pd.DataFrame({'Title': [title], 'Content': [extract]})
df

          Title                                            Content
0  Data science  Data science is an interdisciplinary academic ...

In [ ]:
#tampilan akhirnya
judul = page["title"]
isi = page["extract"]
print("Judul Artikel:", judul)
print("Isi Artikel:", isi)

Judul Artikel: Data science
Isi Artikel: Data science is an interdisciplinary academic field that uses statistics, scientific computing, scientific methods, processing, scientific visualization, algorithms, coding (like Python, SQL, and R), and systems to extract or extrapolate knowledge from potentially noisy, structured, or unstructured data. A data scientist is a professional who creates programming code and combines it with statistical knowledge to summarize data.


== Scope of data science ==
Data science plays a critical role in modern decision-making by enabling organizations to extract actionable insights from large and complex datasets.
Data science also integrates domain knowledge from the underlying application domain (e.g., natural sciences, information technology, and medicine). Data science is multifaceted and can be described as a science, a research paradigm, a research method, a discipline, a workflow, and a profession.
Data science is "a concept to unify statistics, data analysis, informatics, and their related methods" to "understand and analyze actual phenomena" with data. It uses techniques and theories drawn from many fields within the context of mathematics, statistics, computer science, information science, and domain knowledge. However, data science is distinct from computer science and information science. Turing Award winner Jim Gray imagined data science as a "fourth paradigm" of science (empirical, theoretical, computational, and now data-driven) and asserted that "everything about science is changing because of the impact of information technology" and the data deluge.
Data science is often described as a multidisciplinary and rapidly evolving field because it draws on techniques from diverse areas, such as computer science, statistics, information science, and other subject-specific disciplines. Some researchers argue that the combination of the different fields resembles how information science was decades ago. These similarities help clarify how data science gradually became its own field of study.


== Foundations ==
Data science is an interdisciplinary field focused on extracting knowledge from typically large data sets and applying the knowledge from that data to solve problems in other application domains. The field encompasses preparing data for analysis, formulating data science problems, analyzing data, and summarizing these findings. As such, it incorporates skills from computer science, mathematics, data visualization, graphic design, communication, and business.
Vasant Dhar writes that statistics emphasizes quantitative data and description. In contrast, data science deals with quantitative and qualitative data (e.g., from images, text, sensors, transactions, customer information, etc.) and emphasizes prediction and action. Andrew Gelman of Columbia University has described statistics as a non-essential part of data science. Stanford professor David Donoho writes that data science is not distinguished from statistics by the size of datasets or use of computing and that many graduate programs misleadingly advertise their analytics and statistics training as the essence of a data-science program. He describes data science as an applied field growing out of traditional statistics.


== Etymology ==


=== Early usage ===
In 1962, John Tukey described a field he called "data analysis", which resembles modern data science. In 1985, in a lecture given to the Chinese Academy of Sciences in Beijing, C. F. Jeff Wu used the term "data science" for the first time as an alternative name for statistics. Later, attendees at a 1992 statistics symposium at the University of Montpellier  II acknowledged the emergence of a new discipline focused on data of various origins and forms, combining established concepts and principles of statistics and data analysis with computing.
The term "data science" has been traced back to 1974, when Peter Naur proposed it as an alternative name to computer science. In his 1974 book Concise Survey of Computer Methods, Peter Naur proposed using the term ‘data science’ rather than ‘computer science’ to reflect the growing emphasis on data-driven methods In 1996, the International Federation of Classification Societies became the first conference to specifically feature data science as a topic. However, the definition was still in flux. After the 1985 lecture at the Chinese Academy of Sciences in Beijing, in 1997 C. F. Jeff Wu again suggested that statistics should be renamed data science. He reasoned that a new name would help statistics shed inaccurate stereotypes, such as being synonymous with accounting or limited to describing data. In 1998, Hayashi Chikio argued for data science as a new, interdisciplinary concept, with three aspects: data design, collection, and analysis.


=== Modern usage ===
In 2012, technologists Thomas H. Davenport and DJ Patil declared "Data Scientist: The Sexiest Job of the 21st Century", a catchphrase that was picked up even by major-city newspapers like the New York Times and the Boston Globe. A decade later, they reaffirmed it, stating that "the job is more in demand than ever with employers".
The modern conception of data science as an independent discipline is sometimes attributed to William S. Cleveland. In 2014, the American Statistical Association's Section on Statistical Learning and Data Mining changed its name to the Section on Statistical Learning and Data Science, reflecting the ascendant popularity of data science.
The professional title of "data scientist" has been attributed to DJ Patil and Jeff Hammerbacher in 2008. Though it was used by the National Science Board in their 2005 report "Long-Lived Digital Data Collections: Enabling Research and Education in the 21st Century", it referred broadly to any key role in managing a digital data collection.


== Data science and data analysis ==

Data analysis typically involves working with structured datasets to answer specific questions or solve specific problems. This can involve tasks such as data cleaning and data visualization to summarize data and develop hypotheses about relationships between variables. Data analysts typically use statistical methods to test these hypotheses and draw conclusions from the data.
Data science involves working with larger datasets that often require advanced computational and statistical methods to analyze. Data scientists often work with unstructured data such as text or images and use machine learning algorithms to build predictive models. Data science often uses statistical analysis, data preprocessing, and supervised learning.


== Cloud computing for data science ==

Cloud computing can offer access to large amounts of computational power and storage. In big data, where volumes of information are continually generated and processed, these platforms can be used to handle complex and resource-intensive analytical tasks.
Some distributed computing frameworks are designed to handle big data workloads. These frameworks can enable data scientists to process and analyze large datasets in parallel, which can reduce processing times.


== Ethical consideration in data science ==
Data science involves collecting, processing, and analyzing data which often includes personal and sensitive information. Ethical concerns include potential privacy violations, bias perpetuation, and negative societal impacts.
Machine learning models can amplify existing biases present in training data, leading to discriminatory or unfair outcomes.


== See also ==

Python (programming language)
R (programming language)
Data engineering
Big data
Machine learning
Artificial intelligence
Bioinformatics
Astroinformatics
Topological data analysis
List of data science journals
List of data science software
List of open-source data science software
Data science notebook software


== References ==